/**
 * Sentence data pack
 * Finnish sayings, from here:
 * http://fi.wikiquote.org/wiki/Suomalaisia_sananlaskuja
 *
 * @package Pikanakit
 */

Pikanakit.Sentences.DefaultSet = {
	meta : {
		name       : 'Default sentence set',
		language   : 'fi',
		difficulty : 100
	},
	data : [
		'Ei sanottu sana suuhun palaa.',
		'Ei savua ilman tulta.',
		'Ei se eilisen teeren poika ole.',
		'Ei se helvettikhä niin kuuma ole, kun pappi sen saarnaa.',
		'Ei se lapsi ikinä itse kävele, jota aina talutetaan.',
		'Ei se ota jos ei annakaan.',
		'Ei se paljon valehtele, joka puolet valehtelee.',
		'Ei se pelaa joka pelkää.',
		'Ei se putoaminen vaan se äkkipysäys',
		'Ei se tapojansa paranna, joka ei mieltänsä pahoita.',
		'Ei sellaista tietä, jota ei ennen ole käyty.',
		'Ei siitä sydän kuole, mitä ei silmä näe.',
		'Ei silmä osaa ota.',
		'Ei sitä kortilla autoa ajeta.',
		'Ei sitä koskaan tiedä mis puus piru istuu...',
		'Ei sota sanomittaan mene.',
		'Ei sota yhtä miestä kaipaa.',
		'Ei sotamieskään sika ole, jos ei kovin suuri herrakaan.',
		'Ei sovi suopetäjä korpikuusen kumppaniksi.',
		'Ei susi silmiänsä häpee.',
		'Ei suuret sanat suuta halkaise.',
		'Hulluilla on halvat huvit.',
		'Hullu mies Huittisista, syö enemmän kuin tienaa.',
		'Hullu paljon työtä tekee, viisas pääsee vähemmällä.',
		'Hulluja on 99 eri lajia ja kärrihurjat erittäin.',
		'Hulluja on 99 eri lajia ja hulluin on se, joka paskalla ollessaan laulaa.',
		'Hullulla halvat huvit, viisaalla vielä halvemmat.',
		'Hullulla halvat huvit, idiootilla ilmaiset.',
		'Hullun eväs ensin syödään.',
		'Hulluna on hyvä olla kun ei vain järki puutu.',
		'Hullu niin kylpee, että nahka lähtee.',
		'Hullu ei huomaa, eikä viisas sano mitään.',
		'Ihminen päättää, Jumala säätää.',
		'Ihminen se pappikin on.',
		'Ihmisen elanto on orjuuden olento.',
		'Ihmisen pää on kuin sauna; jos pidät liian kauan ovea auki, karkaa lämpö sisältä.',
		'Ilmaiseksi saatu henki, läksipä se aamusta tahi illasta.',
		'Ilmainen tulitikku voi tulla kalliiksi, jos poltat talosi.',
		'Ilman muuta ja muut ilman.',
		'Ilman siipiä ei lintukaan voi lentää.',
		'Ilo ilman viinaa on teeskentelyä.',
		'Joka toista haukkuu, sen napa paukkuu ja se pannaan mustalaisen räkälaukkuun.',
		'Joka tyttönä toruu, se akkana tappelee.',
		'Joka uniinsa uskoo, se varjoaan pelkää',
		'Joka vanhoja muistelee, sitä tikulla silmään.',
		'Juosten on matka joutuisampi.',
		'Jyrki, Jyrki, älä tyrki!',
		'Jäi kuin Jämsän äijä taivaasta.',
		'Jäljestään jäniskin tunnetaan.',
		'Jäljet johtavat sylttytehtaaseen.',
		'Jännittää, sano mummo kun kahvimerkkiä vaihto.',
		'Järkeä kerjätessäkin tarvitaan, ettei kahta kertaa samaan porttiin mennä.',
		'Järki hoi, äly älä jätä!',
		'Kaikki muu on turhaa, paitsi saunominen.',
		'Kaikki on kaunista, kun vaan silmät tottuu.',
		'Kaikki tiet vievät Roomaan.',
		'Kaikki tiiliskiveä pienempi on rakkautta.',
		'Kaikkia meitä hassuttaa mutta eri lailla kutakin.',
		'Kaikkea se sakemanni keksii, sanoi piika kun siilin näki',
		'Kaukaa se on vesikin makeampi.',
		'Kauneus on vain iholla mutta rumuus menee luuhun saakka',
		'Kauneus on katoovaista, mutta rumuus sen kun lisääntyy.',
		'Kaunis on kaunis vain nuorena, mutta ruma on vanhanakin ruma.',
		'Kaunis ääni mutta ammuvainaan nuotti.',
		'Kauniskaan häkki ei anna linnulle ravintoa.',
		'Kaunista kaikki klähmivät, ruman minä otan.',
		'Kauppa se on, joka kannattaa.',
		'Kaupungis menöö rahaa, vaikkei kukkarua aukaasekkaa.',
		'Kaveria ei jätetä!',
		'Kaverille ei jätetä!',
		'Keitä munaa, et saa lientä, neuvo hullua, et saa mieltä.',
		'Kell\' onni on, se onnen kätkeköön.',
		'Kelle paljon annetaan, siltä paljon vaaditaan.',
		'Kellon potut ja Patelan vitut, ne on maankuuluja.',
		'Kellä on maltti, sillä on valtti.',
		'Kellä on paikka paikan päällä, sillä on markka markan päällä.',
		'Kellä vittu, sillä valta. (nainen on parisuhteen päättäjä).',
		'Ken elää, se näkee.',
		'Ken toiselle kuoppaa kaivaa, se itse siihen lankeaa.',
		'Ken toista haukkuu se itse on, ken itseään haukkuu se toinen on.',
		'Kenellä olutta, sillä ystäviä.',
		'Kutina pahenee raapimalla.',
		'Kyllä aikaa on, mutta ikä loppuu.',
		'Kyllä haudassa aikaa maata on.',
		'Kyllä herrat syö vaikka lastuja, kunhan ne voissa paistetaan.¨',
		'Kyllä hätä keinot keksii.',
		'Kyllä Jumala hullut hoitaa, katsokoot viisaat eteensä.',
		'Kyllä kansa muistaa.',
		'Kyllä koira haavansa nuolee.',
		'Kyllä koira koiran tuntee.',
		'Kyllä kesä kuivaa, minkä kasteleekin.',
		'Kyllä kukko aina kanan voittaa.',
		'Kyllä luonto luokse tuopi, veri vierelle vetääpi.',
		'Kyllä laiska kaikkein ahkerin on kun vain ryypyn saa',
		'Kyllä leipä miehen tiellä pitää.',
		'Kyllä lyöpä aseen löytää: sieppaa kengän jalastaan.',
		'Kyllä maa omansa perii.',
		'Kyllä maailma laahaa.',
		'Kyllä maailmaan ääntä mahtuu.',
		'Kyllä maailmanranta neuvoo, vaan kallispalkkainen se on opettajaksi.',
		'Kyllä muisti mummon tiellä pitää.',
		'Kyllä luonto tikanpojan puuhun ajaa.',
		'Kyllä köyhä köyhän löytää.',
		'Kyllä mies aina uuden vaimon saa, mutta lapsi ei saakaan äitiä.',
		'Kyllä muori syitä löytää, kun ei kuolla tahdo.',
		'Kyllä mies kissan nostaa, jos häntä kestää.',
		'Levis ku Hujasen paska Kilipijärven jiälle.',
		'Loistaa kuin yökylypijän perse',
		'Loppui lyhyeen kuin kanan lento.',
		'Loppui lyhyeen kuin Räikkösen ralli.',
		'Lopussa kiitos seisoo.',
		'Lukea kuin piru Raamattua',
		'Luu lihan valitsijalle, kuori leivän alkajalle.',
		'Luulo ei ole tiedon väärti.',
		'Lyödään viisaat päämme yhteen.',
		'Lähtee kuin jänis makuulta.',
		'Lähti ku paska rattaasta.',
		'Lähti ku telkkä pöntöstä.',
		'Lähti kuin Annikki Tähti.',
		'Makuasioista ei voi kiistellä.',
		'Makuasioista ei voi kuin kiistellä.',
		'Maltti on valttia.',
		'Markassa tuhannen alku.',
		'Matti kukkarossa',
		'Matti nauraa pitkällä parralla lapsia seinustalle.',
		'Meitä on moneen junaan, osa jää jo asemalle.',
		'Meijän miniää ei tarvihe nurkista ruoan kanssa essiin huokutella',
		'Men jo, ja vihels mennesäs.',
		'Muija ja kakarat ovat miehen piruja.',
		'Muisti on hyvä mutta lyhyt.',
		'Mummo lumessa ja anoppi kusessa.',
		'Munalla töihin ja pussilla kotiin.',
		'Mun mummoni muni mun mammani, mun mammani muni mun.',
		'Mureaa, sanoi mummo kiisseliä',
		'Murua rinnan alle',
		'Myöhäistä valittaa kun maito on maassa',
		'Myöhäistä itkeä kun on jo paskat housussa.',
		'Myöhäst rutist ko pask o housuis.',
		'Nousi kuin lehmä makuulta.',
		'Nuorena vitsa väännettävä.',
		'Nuoruus on nuoruuden tuhlaamista.',
		'Nuttu nurin päin, onni oikein päin.',
		'"Nyt", sano mummo ja pyörtyi.',
		'Nälkä kasvaa syödessä',
		'Nälkä on paras kokki',
		'On niitä ihmisiä, mutta on niitä ihmisparkojakin.',
		'On oravalle oikein että käpy on jäässä',
		'On se laiskallakkii kiire lauantaina.',
		'On taottava silloin, kun rauta on kuuma.',
		'On vuohellakin parta vaan ei miehen mieltä.',
		'On vähäkin tyhjää parempi.',
		'Onhan niitä nuoriakin kunnanvaivaisia.',
		'Onnistuuhan se Iiläiseltäkin.',
		'Parempi päivä elettynä kuin kaksi kuoltuna.',
		'Parempi virsta väärää kuin vaaksa vaaraa.',
		'Parempi vähän annettu kuin paljon luvattu.',
		'Pata kattilaa soimaa, musta kylki kummallakin.',
		'Paska reissu mutta tulipahan tehtyä.',
		'Paskalla käy herrakin.',
		'Pennissä on miljoonan alku.',
		'Peremmälle sanoi piru kerjäläiselle.',
		'Peukalo keskellä kämmentä.',
		'Pienet lapset, pienet surut, suuret lapset, suuret surut.',
		'Pienellä miehellä isot puhheet.',
		'Pieni pahantekijä hirtetään, suuri usein hirttäjänä.',
		'Pienilläkin padoilla on korvat.',
		'Pieniä ne on silakat joulukaloiksi.',
		'Piimällä ei kasva ku isoot nyrkit ja jyrkät olkapäät.',
		'Pilkka sattuu omaan nilkkaan.',
		'Pitkä kuin nälkävuosi.',
		'Pitäs lähtee, sano kärpänen, ku tervaan tarttu.',
		'Pitää [jostakin] kuin hullu puurosta.'
	]
};

// EOF