/**
 * Sentence data pack
 * Swedish proverbs, from here:
 * http://sv.wikipedia.org/wiki/Lista_%C3%B6ver_svenska_idiomatiska_uttryck
 *
 * @package Pikanakit
 */
Pikanakit.Sentences.SwedishProverbs = {
	meta : {
		name       : 'Swedish proverbs sentence set',
		language   : 'se',
		difficulty : 100
	},
	data : [
		'Damma av något',
		'Dansa efter någons pipa',
		'Dansa på någons grav',
		'Dansen kring den gyllene kalven',
		'Den dagen den sorgen',
		'Den fula ankungen',
		'Den går inte av för hackor',
		'Den/det går loss på xxx',
		'Den gubben går/gick inte',
		'Den röda tråden',
		'Den svagaste länken i kedjan',
		'Det allena saliggörande',
		'Det barkar åt skogen',
		'Det blåser/blåste upp till snus',
		'Det brinner i knutarna',
		'Det drar ihop sig',
		'Det gick som smort',
		'Det fina i kråksången',
		'Det går/gick sin gilla gång',
		'Det går/gick som på räls',
		'Det går/gick som tåget',
		'Det går/gick åt pipan',
		'Det går/gick åt som smör i solsken',
		'Det gick åt skogen',
		'Det har gått troll i något',
		'Det hänger på ett hår',
		'Det hänger på gärsgårn',
		'Det kan du/ni skriva under på!',
		'Det kan du/ni skriva upp!',
		'Det knallar och går',
		'Det lyser, men ingen är hemma',
		'Det man inte har i huvudet får man ha i benen.',
		'Det må väl vara hänt',
		'Det osar katt',
		'Det rullar på',
		'Det står och väger',
		'Det var nära ögat',
		'Det vete fåglarna',
		'Det är detaljerna som gör det',
		'Det är där skon klämmer',
		'Det är grönt',
		'Det är hugget som stucket',
		'Det är full rulle',
		'Dit vindarna bär',
		'Dra/skära/ta alla över en/samma kam eller låta alla gå över samma kam',
		'Dra det längsta/kortaste stråt',
		'Dra ett streck över det som varit',
		'Dra i trådarna',
		'Dra mig baklänges',
		'Dra något i långbänk',
		'Dra något till sin spets',
		'Dra på trissor',
		'Dra sin sista suck',
		'Dra sitt strå till stacken',
		'Dra timmerstockar',
		'Dra det tyngsta lasset',
		'Dra ut på något',
		'Dra ut på tiden',
		'Dra växlar på något',
		'Dra åt Häcklefjäll',
		'Dra åt svångremmen',
		'Dra öronen åt sig',
		'Dragen vid näsan',
		'Droppen som fick bägaren att rinna över',
		'Dum som tåget',
		'Därom tvista de lärde',
		'Därtill är jag nödd och tvungen',
		'Elda för kråkorna',
		'Elefant i en porslinsaffär/porslinsbutik',
		'En annan femma',
		'En black om foten',
		'En droppe i havet',
		'En fjäder i hatten',
		'En fågel har viskat i mitt öra',
		'En gång för alla',
		'En hund begraven',
		'En klapp på axeln',
		'En krösus',
		'En ond cirkel',
		'En salig röra',
		'En skänk från ovan',
		'En stötesten',
		'En sund själ i en sund kropp',
		'En vacker dag',
		'En vit lögn',
		'Ertappas med fingrarna i kakburken/syltburken',
		'Ett hår av Hin',
		'Ett litet korn av sanning',
		'Ett rött skynke.',
		'Ett slag i luften',
		'Ett streck i räkningen',
		'Ett äpple om dagen håller doktorn borta',
		'Flyga i luften',
		'Flyta ovanpå',
		'Från ax till limpa',
		'Full som en alika',
		'Få betalt under bordet',
		'Få blod på händerna',
		'Få blodad tand',
		'Få det hett om öronen',
		'Få eldavbrott[källa behövs]',
		'Få ett kok stryk',
		'Få för gammal ost',
		'Få fötter',
		'Få kalla fötter',
		'Få kalla handen',
		'Få kalla kårar',
		'Få korgen',
		'Få napp',
		'Få något om bakfoten',
		'Få något på hjärnan',
		'Få något på rätt köl',
		'Få något som plåster på såren',
		'Få något till livs',
		'Få nöja sig med smulorna från den rikes bord',
		'Få på båten',
		'Få på pälsen',
		'Få på tafsen',
		'Få saker ur händerna',
		'Få silkessnöret',
		'Få sin beskärda del',
		'Få sina fiskar varma',
		'Få sista ordet',
		'Få ståpäls',
		'Få svar på tal',
		'Få tala till punkt',
		'Få upp ögonen för',
		'Få vatten på sin kvarn',
		'Få veta att man lever',
		'Få ändan ur vagnen',
		'Född i farstun',
		'Följa någon hack i häl',
		'För allt smör i Småland',
		'För allt vad tygen håller',
		'För fulla muggar',
		'För hela slanten',
		'För Kung och fosterland',
		'Förd bakom ljuset',
		'Ge dålig eftersmak',
		'Ge grönt ljus',
		'Ge järnet',
		'Ge igen för gammal ost',
		'Ge någon fria tyglar',
		'Ge någon korgen',
		'Ge sig i kast (med)',
		'Ge sig till att',
		'Ge sig till känna',
		'Ge vid handen (att)',
		'Ge svar på tal',
		'Gilla läget',
		'Gjuta olja på vågorna',
		'Glida in (eller med) på en räkmacka',
		'Glimten i ögat',
		'Goddag yxskaft',
		'Grannens gräs är alltid grönare',
		'Greppa efter ett halmstrå',
		'Griller i huvudet',
		'Gripa tillfället i flykten',
		'Gråa håret',
		'Gråta hela vägen till banken',
		'Gråta över spilld mjölk',
		'Grädde(n) på moset',
		'Gräva där man står',
		'Gräva ner sig i något',
		'Gräva ner stridsyxorna',
		'Gräva sin egen grav',
		'Grön av avund',
		'Gudars skymning!',
		'Gå av för hackor',
		'Gå av stapeln',
		'Gå bort',
		'Ha alla taggar utåt',
		'"Ha eld i baken" illustrerat i Nederländska ordspråk från 1559',
		'Ha eld i baken',
		'Ha en bulle i ugnen',
		'Ha en käpphäst',
		'Ha en oplockad gås med någon',
		'Ha en räv bakom örat',
		'Ha en skruv lös',
		'Ha ett ess i rockärmen',
		'Ha ett finger med i leken',
		'Ha ett horn i sidan till någon',
		'Ha ett rött öre',
		'Ha god hand med',
		'Ha gröna fingrar',
		'Ha huvudet på skaft',
		'Ha/stoppa huvudet under armen',
		'Ha myror i byxorna',
		'Ha många bollar i luften',
		'Ha många järn i elden',
		'Ha många strängar på sin lyra',
		'Ha nio liv',
		'Ha något i ryggmärgen',
		'Ha något i släptåg',
		'Ha något på tungan',
		'Ha något/någon som i en liten ask',
		'Ha näsan i vädret',
		'Ha pippi på något',
		'Ha på fötterna',
		'Ha rent mjöl i påsen',
		'Ha råg i ryggen',
		'Ha satt sin sista potatis',
		'Ha sitt på det torra',
		'Ha skinn på näsan',
		'Ha spenderbyxorna på sig',
		'Ha sålt smöret och tappat pengarna',
		'Ha tomtar på loftet',
		'Ha/vara tumme med någon/något',
		'Ha tummen mitt i handen',
		'Ha vaknat på fel sida',
		'Ha vassa armbågar',
		'Ha vind i seglen',
		'Ha änglavakt',
		'Ha ögon i nacken',
		'Halka in på ett bananskal',
		'Hals över huvud',
		'Hamna i blåsväder',
		'Hamna på överblivna kartan',
		'Hungrig som en varg',
		'Huvuden kommer att rulla',
		'Hålla alla trådar i sin hand',
		'Hålla fanan högt',
		'Hålla god min',
		'Hålla grytan kokande',
		'Hålla i rodret',
		'Hålla låda',
		'Hålla någon kort',
		'Hålla masken',
		'Hålla någon på halster',
		'Hålla någon på sträckbänken',
		'Hålla någon stången',
		'Hålla rumpan styv i kurvorna',
		'Hålla skenet uppe',
		'Hålla sig i skinnet',
		'Hålla sig på mattan',
		'Hålla sig på sin kant',
		'Hålla tand för tunga',
		'Hålla tummarna för någon/något',
		'Hålla tungan rätt i mun',
		'Hålla varandra om ryggen',
		'Hålla ångan uppe',
		'Hålla ögonen på något',
		'I ett nötskal',
		'I eftertankens kranka blekhet',
		'I grevens tid',
		'I kölvattnet',
		'I Simons tid',
		'I sin krafts dagar',
		'I sinom tid',
		'I sitt anletes svett',
		'I stridens hetta',
		'I svinottan',
		'I tid och otid',
		'I ur och skur',
		'In alles, även inalles',
		'In genom ena örat och ut genom andra',
		'Ingen dans på rosor',
		'Ingen fara på taket så länge skorstenen står',
		'Inget man snyter ur näsan',
		'Intet (är) nytt under solen',
		'Intresseklubben antecknar',
		'Intresseflagg',
		'I rödaste rappet',
		'I sus och dus',
		'Kacka i eget bo',
		'Kaka på kaka, även tårta på tårta',
		'Kalv på grönbete',
		'Kamma noll',
		'Kasta ett getöga på någon/något',
		'Kasta ett öga på någon/något',
		'Kasta goda pengar efter dåliga',
		'Kasta in handduken',
		'Kasta (nytt) ljus över något',
		'Kasta loss',
		'I Nederländska ordspråk från 1559 illustreras en man med rosor och ordspråket "Rosen (Perlen) vor die Säue werfen"',
		'Kasta pärlor för svin',
		'Kasta sten i glashus',
		'Kasta ut barnet med badvattnet',
		'Kasta yxan i sjön',
		'Katt bland hermelinerna',
		'Katt på hett plåttak',
		'Katten på råttan, råttan på repet..',
		'Kattens lek med råttan',
		'Kejsarens nya kläder',
		'Klappat och klart',
		'Klockrent',
		'Klok som en pudel',
		'Klubbad säl',
		'Klä sig i säck och aska',
		'Klä skott',
		'Knaka i fogarna',
		'Knyta sig',
		'Knyta till/ihop säcken',
		'Knäpp på näsan',
		'Ligga någon till last',
		'Ligga på',
		'Ligga på sofflocket',
		'Lika goda kålsupare.',
		'Lika som bär',
		'Lite här och var',
		'Liv i luckan',
		'Ljuga sig blå',
		'Ljuga som hästar travar',
		'Ljuger så han/hon tror sig själv',
		'Lova guld och gröna skogar',
		'Lova runt och hålla tunt',
		'Lova vitt och brett',
		'Luktar/smakar pyton',
		'Lyckans ost',
		'Lyfta på förlåten',
		'Lyfta på hatten för',
		'Lyfta sig själv i håret',
		'Lysa med sin frånvaro',
		'Lyset är på men det är ingen hemma',
		'Långt från ära och redlighet',
		'Låta bilan falla',
		'Låta målvakten stå i mål',
		'Låtsas som om det regnar',
		'Läcka som ett såll',
		'Lägga alla ägg i samma korg',
		'Lägga benen på ryggen',
		'Lägga en hämsko på något',
		'Lägga fingrarna emellan',
		'Lägga i malpåse',
		'Nagelfara något',
		'Nu gick det upp ett Liljeholmens',
		'Nu går skam på torra land',
		'Nu trillade polletten ner',
		'Nu är goda råd dyra',
		'Nu är jag ute på okänt vatten',
		'Nu är måttet rågat',
		'Något har sett/ser dagens ljus',
		'Något i hästväg',
		'Något som katten släpat in',
		'Något är som ett gift',
		'När andan faller på',
		'När det kommer till kritan',
		'När krubban är tom bits hästarna',
		'När skoputsarna frågar om aktietips är det dags att sälja',
		'Nära en orm vid sin barm',
		'Närma sig med stormsteg',
		'Odla sin kål',
		'Om inte om hade funnits',
		'Ord står mot ord',
		'Ord och inga visor',
		'Ordning och reda, pengar på freda',
		'Ormens väg på hälleberget',
		'Osvuret är bäst',
		'Pompa och ståt',
		'Prata bredvid mun',
		'Prata i nattmössan',
		'Prata smörja',
		'Pricken över i:et.',
		'Pudelns kärna',
		'På alla fyra',
		'På en höft',
		'På gräsrotsnivå',
		'På kornet',
		'På lösa boliner',
		'På papperet',
		'På pickalurven',
		'På pin kiv',
		'På pricken',
		'På rak arm',
		'På sandlådenivå',
		'På sin mammas gata',
		'På stående fot',
		'Rinna ut i sanden',
		'Rubb och stubb',
		'Rulla hatt',
		'Råka i luven på varandra',
		'Råttorna lämnar ett sjunkande skepp',
		'Räfst och rättarting',
		'Ränderna går aldrig ur',
		'Röra runt/om i grytan',
		'Röra upp himmel och jord',
		'Sagt och gjort',
		'Saken är biff',
		'Sakta men säkert',
		'Satsa på fel häst',
		'Samla i ladorna',
		'Sanningens minut',
		'Se en levande själ',
		'Se färg torka',
		'Se ljuset i tunneln',
		'Se med blida ögon på',
		'Se mellan fingrarna',
		'Se om sitt hus',
		'Se röken av',
		'Se rött',
		'Se sanningen i vitögat',
		'Se skogen för alla träd',
		'Se ut som en fågelholk',
		'Se ut som sju svåra år',
		'Sedan dess har det flutit mycket vatten under broarna',
		'Sedan Eldkvarn brann[källa behövs]',
		'Ser ut som en svinstia',
		'Serverat som på silverfat',
		'Sila mygg och svälja kameler',
		'Sist men inte minst',
		'Sista spiken i kistan',
		'Skållat troll',
		'Skörda sina frukter',
		'Slag under bältet',
		'Slit den med hälsan!',
		'Slita ont',
		'Sluta leden',
		'Slå blå dunster i någon/några',
		'Slå dig/er i backen på',
		'Slå dövörat till',
		'Slå en sjua',
		'Slå en parabel',
		'Slå ett slag för något',
		'Slå huvudet på spiken',
		'Slå i taket',
		'Slå in öppna dörrar',
		'Slå klackarna i taket',
		'Slå knut på sig själv',
		'Slå mynt av något',
		'Slå ner sina bopålar',
		'Slå någon gul och blå',
		'Slå någon/något sönder och samman',
		'Slå näven i bordet',
		'Slå på stora trumman',
		'Slå på stort',
		'Tidens tand',
		'Tids nog',
		'Till råga på allt',
		'Till syvende och sist',
		'Till yttermera visso',
		'Titta för djupt i glaset',
		'Tomma ord',
		'Torrt skinn[ifrågasatt uppgift]',
		'Trampa i klaveret',
		'Trampa inte rödbetor i mossen',
		'Trampa på en öm tå',
		'Trampa vatten',
		'Tredje gången gillt',
		'Tretton på dussinet',
		'Trilla av pinn',
		'Trolla med knäna',
		'Tror, det gör man i kyrkan',
		'Trycka ner i skoskaften',
		'Tulipanaros',
		'Tummen i ögat',
		'Tycka skjortan är trång',
		'Vara i krokarna',
		'Vara i ropet',
		'Vara i sin linda',
		'Vara i sitt esse',
		'Vara i sjunde himlen',
		'Vara karl för sin hatt',
		'Vara körd i botten',
		'Vara med på noterna',
		'Vara om sig och kring sig',
		'Vara på efterkälken',
		'Vara på fallrepet',
		'Vara på fri fot',
		'Vara på glid',
		'Ända in i kaklet',
		'Ända ut i fingerspetsarna',
		'Är ett oskrivet blad',
		'Är i mångt och mycket',
		'Är inte mycket att hänga i julgranen'
	]
};

// EOF